-- DROPS --
DROP TABLE QUEUE

-- CREATE TABLES -- 
CREATE TABLE QUEUE (
QUEUEID INTEGER GENERATED ALWAYS AS IDENTITY,
TIMES Timestamp,
USERS VARCHAR(50),
OV  VARCHAR(50),
COMMENT VARCHAR(50),
STATUS VARCHAR(50),
TABLES VARCHAR(50),
CONSTRAINT QUEUE_pk PRIMARY KEY(QUEUEID));

INSERT INTO QUEUE(QUEUEID, TIMES, USERS, OV, COMMENT, STATUS, TABLES)
VALUES (DEFAULT, CURRENT_TIMESTAMP, 'Ole Olsen', '12', 'HELPZ!', '?', 'SKS table');

INSERT INTO QUEUE(QUEUEID, TIMES, USERS, OV, COMMENT, STATUS, TABLES)
VALUES (DEFAULT, CURRENT_TIMESTAMP, 'ASABAJAN', '12', 'HELPZ!', '?', 'SKS table');

INSERT INTO QUEUE(QUEUEID, TIMES, USERS, OV, COMMENT, STATUS, TABLES)
VALUES (DEFAULT, CURRENT_TIMESTAMP, 'Ole Olsen', '12', 'HELPZ!', '?', 'SKS table');

INSERT INTO QUEUE(QUEUEID, TIMES, USERS, OV, COMMENT, STATUS, TABLES)
VALUES (DEFAULT, CURRENT_TIMESTAMP, 'Ole Olsen', '12', 'HELPZ!', '?', 'SKS table');

